# Generated by Django 4.2.3 on 2025-01-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbaritem',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='navbaritem',
            name='url',
            field=models.SlugField(unique=True),
        ),
    ]
