# Generated by Django 4.2.3 on 2025-01-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_navbaritem_content_alter_navbaritem_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbaritem',
            name='content',
        ),
        migrations.AlterField(
            model_name='navbaritem',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
