# Generated by Django 4.2.3 on 2025-01-31 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_navbaritem_content_alter_navbaritem_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NavbarItem',
            new_name='groupList',
        ),
    ]
