# Generated by Django 4.2.3 on 2025-02-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_navbaritem_grouplist'),
    ]

    operations = [
        migrations.CreateModel(
            name='teachingClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='groupList',
        ),
    ]
