# Generated by Django 4.2.3 on 2025-02-01 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_teachingclass_delete_grouplist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('behaviour_points', models.IntegerField(default=0)),
                ('merits', models.IntegerField(default=0)),
                ('teaching_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='app.teachingclass')),
            ],
        ),
    ]
