# Generated by Django 4.2.3 on 2025-04-09 17:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('behavior_score', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_history', to='app.student')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
