# Generated by Django 4.2.3 on 2025-05-07 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_student_teaching_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teaching_class',
        ),
        migrations.DeleteModel(
            name='teachingClass',
        ),
    ]
